---

- name: Start Servian Tech Challenge Deployment
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files: 
    - '{{ playbook_dir }}/vars/config.yml'
    - '{{ playbook_dir }}/vars/common.yml'

  pre_tasks:

    - name: "Clean Up Build Folder"
      file:
        state: absent
        path: "{{ buildPath }}"
      changed_when: false

    - name: "Create Build Folder"
      file:
        path: "{{ buildPath }}"
        state: directory
        mode: '0755'

  tasks:

    - name: Run Cloudformation Deployment
      import_role:
        name: deploy
      vars: 
        deployItem: "{{ deploy }}"
      when: 
        - state == "present"
        - deploy != "all"

    - name: Run Cloudformation Deployment End to End
      include_role:
        name: deploy
      vars: 
        deployItem: "{{ item }}"
      loop: "{{ all }}"
      when: 
        - state == "present"
        - deploy == "all"

    - name: Destroy Cloudfromation Deployment
      import_role:
        name: destroy
      vars: 
        deployItem: "{{ deploy }}"
      when: 
        - state == "absent"
        - deploy != "all"

    - name: Destroy Cloudformation Deployment End to End
      include_role:
        name: destroy
      vars: 
        deployItem: "{{ item }}"
      loop: "{{ all | reverse | list }}"
      when: 
        - state == "absent"
        - deploy == "all"

  post_tasks:
  
    - name: "Clean Up Build Folder"
      file:
        state: absent
        path: "{{ buildPath }}"
      changed_when: false
