---

alb:
  scheme: internet-facing
  subnets:
    public:
      - a
      - b 
      - c  

ecs:
  container:
    name: techchallenge
    healthCheck: /healthcheck/
    cpu: 256
    memory: 512
    port: 3000
    subnets:
      private:
        - a
        - b
        - c

app:
  cfn:
    parameters:
      HostedZoneId: Z086798223K99DBLKOJ6U
      CertifcateArn: arn:aws:acm:ap-southeast-2:166050580270:certificate/7ed477ff-bf94-4b16-bafb-a495bd2499d4
      TechChallengeUrl: techchallenge.nonprod.navist.com.au
      ContainerImage: cheynembaker/techchallengeapp
