---

alb:
  scheme: internet-facing
  subnets:
    public:
      - a
      - b 
      - c  

ecs:
  container:
    name: techchallenge
    image:
    healthCheck: /healthcheck
    cpu: 256
    memory: 0.5GB
    port: 3000
    subnets:
      private:
        - a
        - b
        - c

  cfn:
    parameters:
      CertifcateArn: arn:aws:acm:ap-southeast-2:166050580270:certificate/7ed477ff-bf94-4b16-bafb-a495bd2499d4
