---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Deploys a route table for the VCP, Internet Gatway and Nat Gatways.

#-------------------------------------------------------------------------------------------------#
# Resources                                                                                       #
#-------------------------------------------------------------------------------------------------#
Resources:
  #-----------------------------------------------------------------------------------------------#
  # Internet Gateway                                                                              #
  #-----------------------------------------------------------------------------------------------# 
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: {{ company }}-vpc-internetgateway
        - Key: VpcId
          Value: !ImportValue {{ company }}-vpc::Vpc

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !ImportValue {{ company }}-vpc::Vpc

  #-----------------------------------------------------------------------------------------------#
  # Nat Gateway                                                                                   #
  #-----------------------------------------------------------------------------------------------# 
  NatGatewayA:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EipA.AllocationId
      SubnetId: !ImportValue {{ company }}-vpc::PublicSubnetA
  EipA:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc
  DefaultPrivateRouteA:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTableA
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGatewayA

  NatGatewayB:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EipB.AllocationId
      SubnetId: !ImportValue {{ company }}-vpc::PublicSubnetB
  EipB:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc
  DefaultPrivateRouteB:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTableB
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGatewayB

  NatGatewayC:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EipC.AllocationId
      SubnetId: !ImportValue {{ company }}-vpc::PublicSubnetB
  EipC:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc
  DefaultPrivateRouteC:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTableC
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGatewayC
  #-----------------------------------------------------------------------------------------------#
  # Public RouteTable                                                                             #
  #-----------------------------------------------------------------------------------------------#   
  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue "{{ company }}-vpc::Vpc"
      Tags:
        - Key: Name
          Value: {{ company }}-vpc-routetable-public

  PublicSubnetAAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !ImportValue {{ company }}-vpc::PublicSubnetA

  PublicSubnetBAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !ImportValue {{ company }}-vpc::PublicSubnetB

  PublicSubnetCAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !ImportValue {{ company }}-vpc::PublicSubnetC

  #-----------------------------------------------------------------------------------------------#
  # Private RouteTable                                                                            #
  #-----------------------------------------------------------------------------------------------#  
  PrivateRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue {{ company }}-vpc::Vpc
      Tags:
        - Key: Name
          Value: {{ company }}-vpc-routetable-private-a

  PrivateRouteTableB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue {{ company }}-vpc::Vpc
      Tags:
        - Key: Name
          Value: {{ company }}-vpc-routetable-private-b

  PrivateRouteTableC:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue {{ company }}-vpc::Vpc
      Tags:
        - Key: Name
          Value: {{ company }}-vpc-routetable-private-c

  PrivateSubnetAAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTableA
      SubnetId: !ImportValue {{ company }}-vpc::PrivateSubnetA

  PrivateSubnetBAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTableB
      SubnetId: !ImportValue {{ company }}-vpc::PrivateSubnetB

  PrivateSubnetCAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTableC
      SubnetId: !ImportValue {{ company }}-vpc::PrivateSubnetC

  #-----------------------------------------------------------------------------------------------#
  # Secure RouteTable                                                                             #
  #-----------------------------------------------------------------------------------------------#  
  SecureRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue {{ company }}-vpc::Vpc
      Tags:
        - Key: Name
          Value: {{ company }}-vpc-routetable-secure

  SecureSubnetAAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref SecureRouteTable
      SubnetId: !ImportValue {{ company }}-vpc::SecureSubnetA

  SecureSubnetBAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref SecureRouteTable
      SubnetId: !ImportValue {{ company }}-vpc::SecureSubnetB

  SecureSubnetCAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref SecureRouteTable
      SubnetId: !ImportValue {{ company }}-vpc::SecureSubnetC
